#!/usr/bin/env python3
"""Deterministic selected-schema compiler for Swift REST wire types."""

from __future__ import annotations

import json
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = json.loads((ROOT / "specs/source.json").read_text())
SPEC = yaml.safe_load((ROOT / "specs/upstream/openapi.yml").read_text())
SCHEMAS = SPEC["components"]["schemas"]
ASYNC_SPEC = yaml.safe_load((ROOT / "specs/upstream/asyncapi.yml").read_text())
ASYNC_SCHEMAS = ASYNC_SPEC["components"]["schemas"]
ROOT_TYPES = ("ListenV1RequestUrl", "ListenV1Response", "ListenV1AcceptedResponse", "SpeakV1Request")
OUTPUT = ROOT / "sdks/swift/Sources/Deepgram/Generated/RestModels.swift"
ASYNC_OUTPUT = OUTPUT.with_name("AsyncModels.swift")
ASYNC_ROOT_TYPES = (
    "ListenV1_ListenV1Results", "ListenV1_ListenV1Metadata", "ListenV1_ListenV1UtteranceEnd",
    "ListenV1_ListenV1SpeechStarted", "ListenV2_ListenV2Connected", "ListenV2_ListenV2TurnInfo",
    "ListenV2_ListenV2ConfigureSuccess", "ListenV2_ListenV2ConfigureFailure", "ListenV2_ListenV2FatalError",
    "SpeakV1_SpeakV1Metadata", "SpeakV1_SpeakV1Flushed", "SpeakV1_SpeakV1Cleared", "SpeakV1_SpeakV1Warning",
)


def name_for_property(name: str) -> str:
    words = name.split("_")
    result = words[0] + "".join(word.capitalize() for word in words[1:])
    if result in {"operator", "description", "default", "repeat", "protocol", "type", "extension"}:
        return f"`{result}`"
    return result


def reference(schema: dict) -> str:
    return schema["$ref"].split("/")[-1]


def swift_type(schema: dict) -> str:
    if "$ref" in schema:
        return reference(schema)
    kind = schema.get("type")
    if kind == "array":
        return "[" + swift_type(schema["items"]) + "]"
    if kind == "object":
        return "[String: JSONValue]"
    if kind == "string":
        return "WireNumber" if schema.get("title") == "float" else "String"
    if kind == "integer":
        return "Int"
    if kind == "number":
        return "Double"
    if kind == "boolean":
        return "Bool"
    if "oneOf" in schema or kind is None:
        return "JSONValue"
    raise ValueError(f"unsupported schema type: {schema}")


def closure(schemas: dict, roots: tuple[str, ...]) -> list[str]:
    pending = list(roots)
    found = set()
    while pending:
        name = pending.pop()
        if name in found:
            continue
        if name not in schemas:
            raise ValueError(f"unknown schema {name}")
        found.add(name)

        def visit(value: object) -> None:
            if isinstance(value, dict):
                if "$ref" in value:
                    pending.append(reference(value))
                for nested in value.values():
                    visit(nested)
            elif isinstance(value, list):
                for nested in value:
                    visit(nested)

        visit(schemas[name])
    return sorted(found)


def render_schema(name: str, schema: dict) -> list[str]:
    kind = schema.get("type")
    if kind == "array":
        return [f"public typealias {name} = {swift_type(schema)}", ""]
    if kind != "object":
        return [f"public typealias {name} = {swift_type(schema)}", ""]
    properties = schema.get("properties", {})
    if not properties:
        return [f"public typealias {name} = [String: JSONValue]", ""]
    required = set(schema.get("required", []))
    lines = [f"public struct {name}: Codable, Sendable {{"]
    for key, value in properties.items():
        prop = name_for_property(key)
        optional = "" if key in required else "?"
        lines.append(f"    public let {prop}: {swift_type(value)}{optional}")
    if name in {"ListenV1RequestUrl", "SpeakV1Request"}:
        key = "url" if name == "ListenV1RequestUrl" else "text"
        lines += ["", f"    public init({key}: String) {{", f"        self.{key} = {key}", "    }"]
    renamed = [(name_for_property(key), key) for key in properties if name_for_property(key).strip("`") != key]
    if renamed:
        lines += ["", "    enum CodingKeys: String, CodingKey {"]
        for key in properties:
            prop = name_for_property(key)
            if prop.strip("`") == key:
                lines.append(f"        case {prop}")
            else:
                lines.append(f"        case {prop} = \"{key}\"")
        lines.append("    }")
    lines += ["}", ""]
    return lines


def main() -> None:
    # Fail on unsupported schema constructs rather than emitting lossy models.
    lines = [
        "// Generated by generators/swift/generate.py. DO NOT EDIT.",
        f"// Deepgram spec commit: {SOURCE['commit']}",
        "import Foundation", "",
        "public enum GeneratedSpec {",
        f"    public static let commit = \"{SOURCE['commit']}\"",
        "    public static let listenV1Path = \"/v1/listen\"",
        "    public static let speakV1Path = \"/v1/speak\"",
        "}", "",
    ]
    for name in closure(SCHEMAS, ROOT_TYPES):
        lines.extend(render_schema(name, SCHEMAS[name]))
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    lines = [
        "// Generated by generators/swift/generate.py. DO NOT EDIT.",
        f"// Deepgram spec commit: {SOURCE['commit']}",
        "import Foundation", "",
    ]
    for name in closure(ASYNC_SCHEMAS, ASYNC_ROOT_TYPES):
        lines.extend(render_schema(name, ASYNC_SCHEMAS[name]))
    ASYNC_OUTPUT.write_text("\n".join(lines))
    print(f"generated {ASYNC_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
