#!/usr/bin/env python3
"""Generate PHP REST wire models from selected pinned OpenAPI schemas."""

from __future__ import annotations

import json
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = json.loads((ROOT / "specs/source.json").read_text())
REST_SCHEMAS = yaml.safe_load((ROOT / "specs/upstream/openapi.yml").read_text())["components"]["schemas"]
ASYNC_SCHEMAS = yaml.safe_load((ROOT / "specs/upstream/asyncapi.yml").read_text())["components"]["schemas"]
SCHEMAS = REST_SCHEMAS | ASYNC_SCHEMAS
ROOT_TYPES = (
    "ListenV1RequestUrl", "ListenV1Response", "ListenV1AcceptedResponse", "SpeakV1Request",
    "ListenV1_ListenV1Results", "ListenV1_ListenV1Metadata", "ListenV1_ListenV1UtteranceEnd", "ListenV1_ListenV1SpeechStarted",
    "ListenV2_ListenV2Connected", "ListenV2_ListenV2TurnInfo", "ListenV2_ListenV2ConfigureSuccess",
    "ListenV2_ListenV2ConfigureFailure", "ListenV2_ListenV2FatalError",
)
OUTPUT = ROOT / "sdks/php/src/Generated"


def refs(value: object) -> set[str]:
    if isinstance(value, dict):
        result = {value["$ref"].split("/")[-1]} if "$ref" in value else set()
        for nested in value.values():
            result |= refs(nested)
        return result
    if isinstance(value, list):
        result = set()
        for nested in value:
            result |= refs(nested)
        return result
    return set()


def closure() -> list[str]:
    pending, found = list(ROOT_TYPES), set()
    while pending:
        name = pending.pop()
        if name in found:
            continue
        if name not in SCHEMAS:
            raise ValueError(f"unknown schema {name}")
        found.add(name)
        pending.extend(refs(SCHEMAS[name]))
    return sorted(found)


def property_name(name: str) -> str:
    words = name.split("_")
    return words[0] + "".join(word.capitalize() for word in words[1:])


def dereference(schema: dict) -> dict:
    while "$ref" in schema:
        schema = SCHEMAS[schema["$ref"].split("/")[-1]]
    return schema


def php_type(schema: dict) -> str:
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        resolved = dereference(schema)
        return name if resolved.get("type") == "object" and resolved.get("properties") else php_type(resolved)
    kind = schema.get("type")
    if "oneOf" in schema or "anyOf" in schema or kind is None:
        return "mixed"
    return {"array": "array", "object": "array", "string": "float" if schema.get("title") == "float" else "string",
            "number": "float", "integer": "int", "boolean": "bool"}[kind]


def decode_expression(schema: dict, expression: str) -> str:
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        resolved = dereference(schema)
        if resolved.get("type") == "object" and resolved.get("properties"):
            return f"{name}::fromArray(Wire::object({expression}))"
        return decode_expression(resolved, expression)
    kind = schema.get("type")
    if "oneOf" in schema or "anyOf" in schema or kind is None:
        return expression
    if kind == "array":
        item = decode_expression(schema["items"], "$item")
        return f"array_map(static fn (mixed $item): mixed => {item}, Wire::array({expression}))"
    if kind == "object":
        return f"Wire::object({expression})"
    if kind == "string":
        return f"Wire::number({expression})" if schema.get("title") == "float" else f"Wire::string({expression})"
    if kind == "number":
        return f"Wire::number({expression})"
    if kind == "integer":
        return f"Wire::integer({expression})"
    if kind == "boolean":
        return f"Wire::boolean({expression})"
    raise ValueError(f"unsupported property schema {schema}")


def render(name: str, schema: dict) -> str:
    properties = schema.get("properties", {})
    if schema.get("type") != "object" or not properties:
        return ""
    required = set(schema.get("required", []))
    ordered = sorted(properties, key=lambda key: (key not in required, key))
    lines = ["<?php", "declare(strict_types=1);", "", "// Generated by generators/php/generate.py. DO NOT EDIT.",
             f"// Deepgram spec commit: {SOURCE['commit']}", "namespace DeepgramSdkLab\\Generated;", "",
             "use DeepgramSdkLab\\Internal\\Wire;", "use JsonSerializable;", "", f"final readonly class {name} implements JsonSerializable", "{",
             "    public function __construct("]
    for key in ordered:
        kind = php_type(properties[key])
        optional = key not in required
        lines.append(f"        public {'?' if optional and kind != 'mixed' else ''}{kind} ${property_name(key)}{' = null' if optional else ''},")
    lines += ["    ) {}", "", "    /** @param array<string, mixed> $data */", "    public static function fromArray(array $data): self", "    {", "        return new self("]
    for key in ordered:
        raw = f"$data['{key}']"
        expression = decode_expression(properties[key], raw)
        if key in required:
            expression = expression.replace(raw, f"Wire::required($data, '{key}')")
        else:
            expression = f"array_key_exists('{key}', $data) && {raw} !== null ? {expression} : null"
        lines.append(f"            {property_name(key)}: {expression},")
    lines += ["        );", "    }", "", "    /** @return array<string, mixed> */", "    public function jsonSerialize(): array", "    {", "        return ["]
    for key in properties:
        lines.append(f"            '{key}' => $this->{property_name(key)},")
    lines += ["        ];", "    }", "}", ""]
    return "\n".join(lines)


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    expected = set()
    for name in closure():
        content = render(name, SCHEMAS[name])
        if content:
            path = OUTPUT / f"{name}.php"
            path.write_text(content)
            expected.add(path.name)
    for path in OUTPUT.glob("*.php"):
        if path.name not in expected:
            path.unlink()
    (OUTPUT / "SpecVersion.php").write_text(
        "<?php\ndeclare(strict_types=1);\n\n// Generated by generators/php/generate.py. DO NOT EDIT.\n"
        "namespace DeepgramSdkLab\\Generated;\n\nfinal class SpecVersion\n{\n"
        f"    public const COMMIT = '{SOURCE['commit']}';\n"
        "    public const LISTEN_V1_PATH = '/v1/listen';\n"
        "    public const SPEAK_V1_PATH = '/v1/speak';\n}\n"
    )
    print(f"generated {len(expected) + 1} PHP files")


if __name__ == "__main__":
    main()
